# Development overrides - automatically loaded by docker-compose

services:
  backend:
    build:
      target: development
    environment:
      NODE_ENV: development
    # Enable debugging port for development
    ports:
      - "9229:9229"  # Debug port for VS Code
      - "${NESTJS_CONTAINER_PORT}:${NESTJS_PORT}"  # Expose port directly for external access
    # Development-specific volumes for hot reload
    volumes:
      - ./backend/src:/app/src
      - ./backend/test:/app/test
      - ./backend/package.json:/app/package.json
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./backend/nest-cli.json:/app/nest-cli.json
      - ./backend/prisma:/app/prisma
    # File watching for development (Docker Compose v2.22+)
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
          ignore:
            - node_modules/
        - action: sync
          path: ./backend/prisma
          target: /app/prisma
        - action: rebuild
          path: ./backend/package.json
        - action: rebuild
          path: ./backend/yarn.lock
    # Override restart policy for development
    restart: unless-stopped
