# Traefik static configuration for PRODUCTION
global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: false
  debug: false

entryPoints:
  web:
    address: ":80"
    # Redirect HTTP to HTTPS in production
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
  file:
    filename: /etc/traefik/dynamic-prod.yml
    watch: true

# SSL Certificate configuration
certificatesResolvers:
  letsencrypt:
    acme:
      email: "admin@yourdomain.com"  # Update with your email
      storage: /acme.json
      httpChallenge:
        entryPoint: web

log:
  level: WARN

accessLog: {}

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
